logging:
  level:
    root: INFO
mychat:
  swagger:
    title: "mychat项目公共接口文档"
    version: "1.0"
    description: "mychat项目公共接口文档"
    package: "com.wanglongxiang.common.controller"
#mybatis:
#  configuration:
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 8087
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl