spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mychat.jdbc.un}
    password: ${mychat.jdbc.pw}
    url: jdbc:mysql://${mychat.jdbc.localhost}:${mychat.jdbc.port}/${mychat.jdbc.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  profiles:
    active: dev
  redis:
    database: ${mychat.redis.database}
    host: ${mychat.redis.host}
    password: ${mychat.redis.password}
    port: ${mychat.redis.port}
logging:
  level:
    root: INFO
mychat:
  jwt:
#    设置jwt加密密钥
    secret-key: xiaosu
#    设置过期时间
    ttl: 7200000
#    前端传递过来的令牌名称
    token-name: token
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tCXiwTCFQLQNn88Nmkq
    access-key-secret: uv0qVt7yh0qjMIV5UUOUPkItJiSAsF
    bucket-name: sc-mychat

#mybatis:
#  configuration:
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl