logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
mychat:
  swagger:
    title: "mychat项目聊天接口文档"
    version: "1.0"
    description: "mychat项目聊天接口文档"
    package: "com.wanglongxiang.crony.controller"
#mybatis:
#  configuration:
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 8084
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl