logging:
  level:
    root: INFO
mychat:
  jwt:
#    设置jwt加密密钥
    secret-key: xiaosu
#    设置过期时间
    ttl: 7200000
#    前端传递过来的令牌名称
    token-name: token
  swagger:
    title: "mychat项目用户接口文档"
    version: "1.0"
    description: "mychat用户接口文档"
    package: "com.wanglongxiang.user.controller"
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tCXiwTCFQLQNn88Nmkq
    access-key-secret: uv0qVt7yh0qjMIV5UUOUPkItJiSAsF
    bucket-name: sc-mychat
#mybatis:
#  configuration:
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 8088
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl