spring:
  profiles:
    active: local
  application:
    name: common-service
  cloud:
    nacos:
      server-addr: 192.168.85.139:8840
logging:
  level:
    root: INFO
mychat:
  swagger:
    title: "mychat项目公共接口文档"
    version: "1.0"
    description: "mychat项目公共接口文档"
    package: "com.wanglongxiang.chat.controller"
#mybatis:
#  configuration:
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
server:
  port: 8085
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl